id: PBD4B9105
initial_creation_type: ocr
source_metadata:
  volumes:
    0e5017bb0ff845f3a8dcea5f3c7ab76d:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཇམ་པའི་དབྱངས་དཔའ་བོ་གཅིག་ཏུ་གྲུབ་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
